version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts # Official Jenkins Long-Term Support image
    container_name: jenkins
    ports:
      - "8080:8080"  # Expose Jenkins on port 8080
      - "50000:50000" # For Jenkins agents to connect to the master
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Skip setup wizard
    restart: unless-stopped  # Automatically restart Jenkins if it crashes

volumes:
  jenkins_home:  # Volume to persist Jenkins data
    driver: local


